from .Mov import Mov
from .Add import Add
from .Inc import Inc
from .Dec import Dec
from .Jmp import Jmp
from .Jnz import Jnz
from .Cmp import Cmp
from .Noop import Noop
from .Push import Push
from .Pop import Pop
from .Call import Call
from .Ret import Ret
from .Int import Int